messages =  [  
    {'text': 'I hate this food.', 'label': 1},
    {'text': 'This movie is terrible.', 'label': 1},
    {'text': 'I really like this play.', 'label': 0},
    {'text': 'I am just not sure.', 'label': 0},
    {'text': 'I can\'t believe you would do something like that!', 'label': 1},
    {'text': 'This is absolutely unacceptable!', 'label': 1},
    {'text': 'I am so angry right now, I can\'t even think straight.', 'label': 1},
    {'text': 'How could you be so thoughtless?', 'label': 1},
    {'text': 'You have no idea how much you\'ve hurt me.', 'label': 1},
    {'text': 'I\'m so frustrated I could scream.', 'label': 1},
    {'text': 'I\'ve never been so mad in my life!', 'label': 1},
    {'text': 'I can\'t even look at you right now.', 'label': 1},
    {'text': 'You\'ve really crossed the line this time.', 'label': 1},
    {'text': 'I won\'t stand for this kind of behavior.', 'label': 1},
    {'text': 'It\'s a beautiful day outside.', 'label': 0},
    {'text': 'I had a great time at the party last night.', 'label': 0},
    {'text': 'The flowers in the garden are blooming.', 'label': 0},
    {'text': 'I\'m looking forward to my vacation next week.', 'label': 0},
    {'text': 'The new restaurant in town has amazing food.', 'label': 0},
    {'text': 'I love spending time with my family and friends.', 'label': 0},
    {'text': 'The sunset was breathtaking.', 'label': 0},
    {'text': 'I always feel better after going for a run.', 'label': 0},
    {'text': 'The book I just finished reading was really good.', 'label': 0},
    {'text': 'I feel so relaxed after taking a hot bath.', 'label': 0},
    {'text': 'Good case. Excellent value.', 'label': 0},
    {'text': 'Great for the jawbone.', 'label': 0},
    {'text': 'Tied to charger for conversations lasting more than 45 minutes.MAJOR PROBLEMS!!', 'label': 1},
    {'text': 'The mic is great.', 'label': 0},
    {'text': 'I have to jiggle the plug to get it to line up right to get decent volume.', 'label': 0},
    {'text': 'If you have several dozen or several hundred contacts.', 'label': 0},
    {'text': 'then imagine the fun of sending each of them one by one.', 'label': 0},
    {'text': 'If you are Razr owner...you must have this!', 'label': 0},
    {'text': 'Needless to say I wasted my money.', 'label': 1},
    {'text': 'What a waste of money and time!.', 'label': 1},
    {'text': 'And the sound quality is great.', 'label': 0},
    {'text': 'He was very impressed when going from the original battery to the extended battery.', 'label': 0},
    {'text': 'If the two were seperated by a mere 5+ ft I started to notice excessive static and garbled sound fro...', 'label': 0},
    {'text': 'Very good quality though the design is very odd as the ear "clip" is not very comfortable at all.', 'label': 0},
    {'text': 'Highly recommend for any one who has a blue tooth phone.', 'label': 0},
    {'text': 'I advise EVERYONE DO NOT BE FOOLED!', 'label': 1},
    {'text': 'So Far So Good!. Works great!.', 'label': 0},
    {'text': 'It clicks into place in a way that makes you wonder how long that mechanism would last.', 'label': 0},
    {'text': 'I went on Motorola''s website and followed all directions but could not get it to pair again.', 'label': 0},
    {'text': 'I bought this to use with my Kindle Fire and absolutely loved it!', 'label': 0},
    {'text': 'The commercials are the most misleading.', 'label': 1},
    {'text': 'I have yet to run this new battery below two bars and that''s three days without charging. I bought it for my mother and she had a problem with the battery.', 'label': 1},
    {'text': 'Great Pocket PC / phone combination.', 'label': 0},
    {'text': 'I''ve owned this phone for 7 months now and can say that it''s the best mobile phone I''ve had.', 'label': 0},
    {'text': 'I didn''t think that the instructions provided were helpful to me.', 'label': 0},
    {'text': 'People couldnt hear me talk and I had to pull out the earphone and talk on the phone.', 'label': 0},
    {'text': 'Doesn''t hold charge.', 'label': 0},
    {'text': 'This is a simple little phone to use but the breakage is unacceptible.', 'label': 1},
    {'text': 'This product is ideal for people like me whose ears are very sensitive.', 'label': 0},
    {'text': 'It is unusable in a moving car at freeway speed.', 'label': 1},
    {'text': 'I have two more years left in this contract and I hate this phone.', 'label': 1}
]